name: NoxUtils
version: '2.2.0-SNAPSHOT'
main: me.iris.noxUtils.NoxUtils
api-version: '1.21'
authors: [ Iris ]
description: A tool to communicate with Noxesium clients (mostly as an API for usage with Skript-Reflect)
website: https://github.com/BlockybombDEV/NoxUtils
depend:
  - CommandAPI
